[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
utoipa = { workspace = true }
derive_more = { workspace = true }
time = { version = "0.3.36", features = ["serde"] }
